import { createContext } from 'react';
import type { Product, Order, CartItem, Tenant, Driver, OrderStatus, PaymentMethod, Transaction, UserRole, Post, Story, UserAccount, City, Zone, CheckoutDetails, RestaurantApplication, UserLocationState } from '../types';
import type { ApplicationAssetFiles } from '../services/supabaseDataService';

export interface AppContextType {
  cities: City[];
  zones: Zone[];
  selectedCityId: string;
  selectedZoneId: string | null;
  userLocationState: UserLocationState;
  locationPreference: 'gps' | 'manual';
  setSelectedCity: (cityId: string) => void;
  setSelectedZone: (zoneId: string | null) => void;
  refreshCities: () => Promise<void>;
  refreshZones: (cityId?: string) => Promise<void>;
  requestUserLocation: () => Promise<void>;
  clearUserLocation: () => void;
  resolveCityFromCoordinates: (latitude: number, longitude: number) => Promise<boolean>;
  switchToManualLocation: () => void;
  tenants: Tenant[];
  currentTenant: Tenant;
  products: Product[];
  orders: Order[];
  transactions: Transaction[];
  posts: Post[];
  stories: Story[];
  cart: CartItem[];
  drivers: Driver[];
  equityWeight: number;
  authMode: 'remote' | 'demo';
  isAuthLoading: boolean;
  isCatalogLoading: boolean;
  catalogError: string | null;
  remoteTenants: Tenant[];
  remoteProducts: Product[];
  remotePosts: Post[];
  isSubmittingOrder: boolean;
  orderError: string | null;
  userRole: UserRole;
  currentUser: UserAccount | null;
  toast: string | null;
  restaurantApplications: RestaurantApplication[];
  loginWithCredentials: (email: string, pass: string) => Promise<{ success: boolean; error?: string }> | boolean;
  loginWithGoogle: () => Promise<{ success: boolean; error?: string }> | void;
  registerAccount: (name: string, email: string, pass: string, role?: UserRole) => Promise<{ success: boolean; error?: string }> | void;
  sendPasswordReset: (email: string) => Promise<{ success: boolean; error?: string }>;
  setCurrentTenantBySlug: (slug: string) => void;
  toggleTenantOpenStatus: (tenantId: string) => Promise<void>;
  addTenant: (tenantData: Omit<Tenant, 'id' | 'slug' | 'salesWeekly' | 'rating' | 'distanceKm' | 'isNew' | 'commissionRate' | 'tablesCount' | 'isOpen'>) => Tenant;
  updateTenant: (tenantId: string, updates: Partial<Tenant>) => void;
  toggleLikePost: (postId: string) => void;
  addComment: (postId: string, text: string, userName?: string) => Promise<boolean>;
  deleteComment: (postId: string, commentId: string) => void;
  createPost: (postData: Omit<Post, 'id' | 'likes' | 'isLiked' | 'commentsCount' | 'viewCount' | 'ordersFromPost' | 'timeAgo'>) => Promise<void> | void;
  deletePost: (postId: string) => Promise<void> | void;
  addDriver: (driver: Omit<Driver, 'id' | 'tenantId' | 'status'>) => void;
  deleteProduct: (productId: string) => Promise<void> | void;
  setEquityWeight: (weight: number) => void;
  addToCart: (product: Product) => { success: boolean; requiresClear?: boolean; activeTenantName?: string; } | void;
  clearCartAndAdd: (product: Product) => void;
  removeFromCart: (productId: string) => void;
  clearCart: () => void;
  submitOrderWithPayment: (typeOrDetails: string | CheckoutDetails, method: PaymentMethod, transaction?: Transaction) => Promise<{ success: boolean; isRemote?: boolean; orderId?: string; paymentId?: string; sandboxUrl?: string; wompiConfig?: unknown }>;
  retryRemotePayment: (orderId: string) => Promise<{ success: boolean; paymentId?: string; sandboxUrl?: string; wompiConfig?: unknown }>;
  updateOrderStatus: (orderId: string, status: OrderStatus) => Promise<boolean>;
  toggleProductAvailability: (productId: string) => Promise<void> | void;
  addProduct: (product: Omit<Product, 'id' | 'tenantId'>) => Promise<void> | void;
  assignDriverToOrder: (orderId: string, driverId: string) => void;
  submitRestaurantApplication: (applicationData: Omit<RestaurantApplication, 'id' | 'submittedAt' | 'status'>, assets?: ApplicationAssetFiles) => Promise<boolean>;
  reviewRestaurantApplication: (applicationId: string, nextStatus: 'reviewing' | 'approved' | 'rejected', reviewNote?: string) => Promise<boolean>;
  activateApprovedRestaurant: (applicationId: string) => Promise<{ success: boolean; tenantId?: string; error?: string; message?: string }>;
  showToast: (message: string) => void;
  triggerTestOrder: () => void;
  logout: () => void;
}

export const AppContext = createContext<AppContextType | undefined>(undefined);
